### ISSUE TITLE
[WIP]: Prepare to release Hops@latest

### ISSUE THREAD

**Issue by ZauberNerd** [xing/hops#647]
We should soon be able to release Hops 11 on npm as latest.

**checklist**
- [x] remove `fragment-types-loader` and merge #642 
- [x] Fix memory leak in development server #697
- [x] loosen-up Hops/untool dependency ranges (use `^` instead of pinning)
- [x] re-introduce global CSS support #418 
- [ ] identify breaking changes from Hops 10 -> Hops 11
- [ ] write migration guides
- [ ] write release notes
- ... anything else I'm missing?

/cc @robin-drexler @dmbch

**Comment by saviomuc** [comment]
I'd like to add that the changes for rc29 could be breaking for many who still use Babel6: https://github.com/xing/hops/commit/701b5f0 and should be added to the docs. Babel also provides a migration guide: https://babeljs.io/docs/en/v7-migration
